[package]
name = "cyphers"
version = "0.1.0"
authors = ["lucascr91 <lucas.ecomg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"